### ISSUE TITLE
There is no self.ii_image

### ISSUE THREAD

**Issue by SravanChittupalli** [saharshleo/OpenCV-Trackers#3]
https://github.com/saharshleo/OpenCV-Trackers/blob/9a8f6f5ada84678d309749ff413acdab9402a6ed/Boosting/Boosting.py#L64

@amanchhaparia I guess you have to pass Boosting.ii_image.

**Comment by amanchhaparia** [comment]
self.ii_image was redundant for this version code hence it is removed now!
