### ISSUE TITLE
Weight of each sample

### ISSUE THREAD

**Issue by SravanChittupalli** [saharshleo/OpenCV-Trackers#4]
https://github.com/saharshleo/OpenCV-Trackers/blob/9a8f6f5ada84678d309749ff413acdab9402a6ed/Boosting/Boosting.py#L80

I guess the weight of each sample should be 1/self.N

**Comment by amanchhaparia** [comment]
[online-boosting-and-vision.pdf](https://github.com/saharshleo/OpenCV-Trackers/files/5949357/online-boosting-and-vision.pdf)

Refer algorithm 2.1
