### ISSUE TITLE
Minor mistake

### ISSUE THREAD

**Issue by SravanChittupalli** [saharshleo/OpenCV-Trackers#5]
https://github.com/saharshleo/OpenCV-Trackers/blob/9a8f6f5ada84678d309749ff413acdab9402a6ed/Boosting/Boosting.py#L96
https://github.com/saharshleo/OpenCV-Trackers/blob/9a8f6f5ada84678d309749ff413acdab9402a6ed/Boosting/Boosting.py#L100

It shoud be feature.mu_minus+=feature.value_at_sample_pixels[ j ]

**Comment by amanchhaparia** [comment]
i --> refer to the i th sample
j --> refer to the j th feature
therefore feature.value_at_sample_pixels[i] refers to the value of the jth feature at ith sample

**Comment by SravanChittupalli** [comment]
But you are doing it inside the jth loop right?

So you are applying j features on i samples.
